### ISSUE TITLE
Using this in pytorch-grad-cam

### ISSUE THREAD

**Issue by jacobgil** [tleemann/road_evaluation#1]
Hi,

I added this to pytorch-grad-cam !
There is a detailed notebook with an overview of metrics, and a section about ROAD there:
https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/CAM%20Metrics%20And%20Tuning%20Tutorial.ipynb

In class activation maps, the highest attention regions are usually smooth and localized.
When using ROAD, this results in regions that are very blurred.
![image](https://user-images.githubusercontent.com/5342073/178107973-dce9f333-f855-42f1-bfb7-52841b3a66c6.png)
I guess this still leakes information and these areas could be detected.

I was thinking about increasing the level of the noise,
but also was thinking about "seeding" some pixels in the region, maybe pixels in random locations with random colors, before applying ROAD.
Was wondering if you had thoughts about this?

**Comment by tleemann** [comment]
Hi Jacob,
congratulations on your excellent work and thanks for considering our ROAD benchmark! 
I agree, that it will likely be possible for a model to detect these regions. However, in the optimized version of ROAD (no-retraining), the model is not retrained, so the decline in accuracy might still be mainly due to the information "removed". 

From a theoretical standpoint, it is important that the images are imputed in a natural way so the image stays in-distribution. While increasing the noise-level (the best choice would be to match the "noise" in the natural image pixels), might lead to some improvement, I think seeding random colors will probably generate an image that is even further from the original distribution... 
If you want to go the long way, you can try to train a GAN model (we tried this in the revised version of our paper, but for our setup, the difference to the Noisy Linear Imputation was negligible, so we decided to recommend the simpler model in the end), but maybe for smooth regions, there might be a larger benefit.

I hope this helps, 
Tobias

PS: We are updating the code this week for the presentation at the conference. We will also include an example of the GAN imputation. You can already have a look at it in the branch ``road_v2`` but we are still finishing some checks, so there might be some minor issues.
